---
title: "Disyllabic tone sandhi in Lexical Compounds (LC) & Modifier-Head Phrases (MH) in Xiangshan"
Author: 'Yibing Shi'
date: "Last updated: 2024-05-28"
output: 
  html_document:
    toc: true
    toc_float:
      toc_collapsed: true
    toc_depth: 3
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(tidyverse)
library(kableExtra) 
library(ggplot2)
library(gridExtra) 
library(ggthemes)
library(viridis)
library(plotly)
library(ggrepel)
library(kml)
```

# Data preparations  
```{r}
load("/Users/shiyibing/Desktop/PhD/XSTSF/XSTSF_production.RData")
source('/Users/shiyibing/Desktop/PhD/XSTSF/functions.R')
```

```{r}
# normalisation of f0 across all citation tokens
f0_all_ct <- f0_all_pre %>% filter(focus_condition == 'ct' ) %>% 
  group_by(speaker) %>% 
  mutate(norm_f0 = scale(log(f0))) %>% 
  ungroup()

# extract all disyllabic LC & MH
f0_di_ct_lcmh <- f0_all_ct %>% 
  filter(syntax %in% c('L', 'M') & diortri == 'di') %>% 
  mutate(sandhi_tone = case_when(sandhi_tone == 'HLLM' ~ 'HMML',
                                 sandhi_tone == 'LLHL' ~ 'LLRF', 
                                 .default = sandhi_tone)) %>% 
  # remove outliers
  filter(!ind_no %in% c('S2_1_ct', 'S2_11_ct', 'S2_27_ct', 'S3_5_ct', 'S3_19_ct', 'S5_27_ct')) %>% 
  filter(is.na(sandhi_tone) == FALSE) 

# subset H- and L-initial datasets
f0_di_ct_lcmh_h <- f0_di_ct_lcmh %>% filter( grepl('^H', sync_tone1))
f0_di_ct_lcmh_l <- f0_di_ct_lcmh %>% filter( grepl('^[LR]', sync_tone1)) 
```

<br>
<br>

# H-initial dataset

## Auditory categorisation  

```{r out.width = '600px', out.height='350px', message=FALSE, warning=FALSE}
unique(f0_di_ct_lcmh_h$sandhi_tone) # check the categories

p_cluster(f0_di_ct_lcmh_h, sandhi_tone)
```

## k-means clustering
```{r out.width = '600px', out.height='350px',message=FALSE, warning=FALSE}
f0_di_ct_lcmh_h_kmeans <- f0_di_ct_lcmh_h %>% 
  select(-diortri, -syllable_no, -focus_no, -f0) %>% 
  spread(time, norm_f0)
cluster_model <- k_means_clustering(f0_di_ct_lcmh_h_kmeans)
kml(cluster_model, nbClusters = 2:10) 
kml::plot(cluster_model, 4, parTraj=parTRAJ(col="clusters"))
```



## comparisons  between auditory and k-means clustering
```{r out.width = '600px', out.height='400px',message=FALSE, warning=FALSE}
# get cluster results
f0_di_ct_lcmh_h_kmeans <- f0_di_ct_lcmh_h_kmeans %>% 
  mutate(cluster4 = getClusters(cluster_model, 4),
         sub_cluster = paste0(sandhi_tone, '_', cluster4),
         cluster2 = getClusters(cluster_model, 2))

# heatmap distribution
cluster_solution <- wide_to_long(f0_di_ct_lcmh_h_kmeans) 
heatmap_df <- heatmap_data(cluster_solution, cluster4)
compare_cluster(heatmap_df, 'cluster4')
```

<br>
<br>

# L-initial dataset

## Auditory categorisation 

```{r out.width = '600px', out.height='350px',warning=FALSE, message=FALSE}
unique(f0_di_ct_lcmh_l$sandhi_tone) # check the labels

p_cluster(f0_di_ct_lcmh_l, sandhi_tone)
```

## k-means clustering 
```{r out.width = '600px', out.height='350px',message=FALSE, warning=FALSE}
f0_di_ct_lcmh_l_kmeans <- f0_di_ct_lcmh_l %>% 
  select(-diortri, -syllable_no, -focus_no, -f0) %>% 
  spread(time, norm_f0)
cluster_model <- k_means_clustering(f0_di_ct_lcmh_l_kmeans)
kml(cluster_model, nbClusters = 2:10) 
kml::plot(cluster_model, 4, parTraj=parTRAJ(col="clusters"))
```



## comparisons  between auditory and k-means clustering
```{r out.width = '600px', out.height='400px',message=FALSE, warning=FALSE}
f0_di_ct_lcmh_l_kmeans <- f0_di_ct_lcmh_l_kmeans %>% 
  mutate(cluster4 = getClusters(cluster_model, 4),
         cluster3 = getClusters(cluster_model, 3),
         sub_cluster = paste0(sandhi_tone, '_', cluster4)) %>% 
  mutate(sandhi_tone = ifelse(cluster4 == 'C' & sandhi_tone == 'LLLM', 'LLRF', sandhi_tone))

# heatmap distribution
cluster_solution <- wide_to_long(f0_di_ct_lcmh_l_kmeans) 
heatmap_df <- heatmap_data(cluster_solution, cluster4)
compare_cluster(heatmap_df, 'cluster4')
```



